name: Generate README

on:
  push:
    paths:
      - 'solutions/**'
      - 'scripts/gen-readme.js'

permissions:
  contents: write

jobs:
  build-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install deps (none required)
        run: echo "No deps"
      - name: Run generator
        run: node scripts/gen-readme.js
      - name: Commit README
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: update README (auto)" || echo "no changes"
          git push
